// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package fivem

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type fivemSockopsFivemDropHistoryValue struct {
	FirstDropNs uint64
	LastDropNs  uint64
	Counts      [12]uint64
}

type fivemSockopsRatelimit struct {
	Tokens       uint64
	LastRefillNs uint64
}

// loadFivemSockops returns the embedded CollectionSpec for fivemSockops.
func loadFivemSockops() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FivemSockopsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load fivemSockops: %w", err)
	}

	return spec, err
}

// loadFivemSockopsObjects loads fivemSockops and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*fivemSockopsObjects
//	*fivemSockopsPrograms
//	*fivemSockopsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFivemSockopsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFivemSockops()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// fivemSockopsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fivemSockopsSpecs struct {
	fivemSockopsProgramSpecs
	fivemSockopsMapSpecs
	fivemSockopsVariableSpecs
}

// fivemSockopsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fivemSockopsProgramSpecs struct {
	GameshieldFivemSockops *ebpf.ProgramSpec `ebpf:"gameshield_fivem_sockops"`
}

// fivemSockopsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fivemSockopsMapSpecs struct {
	FivemDropHistory     *ebpf.MapSpec `ebpf:"fivem_drop_history"`
	FivemStats           *ebpf.MapSpec `ebpf:"fivem_stats"`
	GetinfoRatelimit     *ebpf.MapSpec `ebpf:"getinfo_ratelimit"`
	InitconnectRatelimit *ebpf.MapSpec `ebpf:"initconnect_ratelimit"`
	TcpEstablished       *ebpf.MapSpec `ebpf:"tcp_established"`
	TcpGlobalRatelimit   *ebpf.MapSpec `ebpf:"tcp_global_ratelimit"`
	TcpOpenCount         *ebpf.MapSpec `ebpf:"tcp_open_count"`
	TcpSynSeen           *ebpf.MapSpec `ebpf:"tcp_syn_seen"`
	TcpWhitelist         *ebpf.MapSpec `ebpf:"tcp_whitelist"`
}

// fivemSockopsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fivemSockopsVariableSpecs struct {
}

// fivemSockopsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFivemSockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type fivemSockopsObjects struct {
	fivemSockopsPrograms
	fivemSockopsMaps
	fivemSockopsVariables
}

func (o *fivemSockopsObjects) Close() error {
	return _FivemSockopsClose(
		&o.fivemSockopsPrograms,
		&o.fivemSockopsMaps,
	)
}

// fivemSockopsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFivemSockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type fivemSockopsMaps struct {
	FivemDropHistory     *ebpf.Map `ebpf:"fivem_drop_history"`
	FivemStats           *ebpf.Map `ebpf:"fivem_stats"`
	GetinfoRatelimit     *ebpf.Map `ebpf:"getinfo_ratelimit"`
	InitconnectRatelimit *ebpf.Map `ebpf:"initconnect_ratelimit"`
	TcpEstablished       *ebpf.Map `ebpf:"tcp_established"`
	TcpGlobalRatelimit   *ebpf.Map `ebpf:"tcp_global_ratelimit"`
	TcpOpenCount         *ebpf.Map `ebpf:"tcp_open_count"`
	TcpSynSeen           *ebpf.Map `ebpf:"tcp_syn_seen"`
	TcpWhitelist         *ebpf.Map `ebpf:"tcp_whitelist"`
}

func (m *fivemSockopsMaps) Close() error {
	return _FivemSockopsClose(
		m.FivemDropHistory,
		m.FivemStats,
		m.GetinfoRatelimit,
		m.InitconnectRatelimit,
		m.TcpEstablished,
		m.TcpGlobalRatelimit,
		m.TcpOpenCount,
		m.TcpSynSeen,
		m.TcpWhitelist,
	)
}

// fivemSockopsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFivemSockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type fivemSockopsVariables struct {
}

// fivemSockopsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFivemSockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type fivemSockopsPrograms struct {
	GameshieldFivemSockops *ebpf.Program `ebpf:"gameshield_fivem_sockops"`
}

func (p *fivemSockopsPrograms) Close() error {
	return _FivemSockopsClose(
		p.GameshieldFivemSockops,
	)
}

func _FivemSockopsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed fivemsockops_bpfel.o
var _FivemSockopsBytes []byte
