// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package fivem

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type fivemXDPFivemDropHistoryValue struct {
	FirstDropNs uint64
	LastDropNs  uint64
	Counts      [12]uint64
}

type fivemXDPRatelimit struct {
	Tokens       uint64
	LastRefillNs uint64
}

type fivemXDPUdpHealth struct {
	Anomalies        uint32
	_                [4]byte
	WindowStartNs    uint64
	BlacklistUntilNs uint64
}

// loadFivemXDP returns the embedded CollectionSpec for fivemXDP.
func loadFivemXDP() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FivemXDPBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load fivemXDP: %w", err)
	}

	return spec, err
}

// loadFivemXDPObjects loads fivemXDP and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*fivemXDPObjects
//	*fivemXDPPrograms
//	*fivemXDPMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFivemXDPObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFivemXDP()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// fivemXDPSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fivemXDPSpecs struct {
	fivemXDPProgramSpecs
	fivemXDPMapSpecs
	fivemXDPVariableSpecs
}

// fivemXDPProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fivemXDPProgramSpecs struct {
	GameshieldFivemXdp *ebpf.ProgramSpec `ebpf:"gameshield_fivem_xdp"`
}

// fivemXDPMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fivemXDPMapSpecs struct {
	FivemDropHistory     *ebpf.MapSpec `ebpf:"fivem_drop_history"`
	FivemStats           *ebpf.MapSpec `ebpf:"fivem_stats"`
	GetinfoRatelimit     *ebpf.MapSpec `ebpf:"getinfo_ratelimit"`
	InitconnectRatelimit *ebpf.MapSpec `ebpf:"initconnect_ratelimit"`
	TcpEstablished       *ebpf.MapSpec `ebpf:"tcp_established"`
	TcpGlobalRatelimit   *ebpf.MapSpec `ebpf:"tcp_global_ratelimit"`
	TcpOpenCount         *ebpf.MapSpec `ebpf:"tcp_open_count"`
	TcpSynSeen           *ebpf.MapSpec `ebpf:"tcp_syn_seen"`
	TcpWhitelist         *ebpf.MapSpec `ebpf:"tcp_whitelist"`
	UdpHealth            *ebpf.MapSpec `ebpf:"udp_health"`
	UdpRatelimit         *ebpf.MapSpec `ebpf:"udp_ratelimit"`
}

// fivemXDPVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fivemXDPVariableSpecs struct {
	GetinfoBurst        *ebpf.VariableSpec `ebpf:"getinfo_burst"`
	GetinfoPeriodNs     *ebpf.VariableSpec `ebpf:"getinfo_period_ns"`
	HealthBlacklistNs   *ebpf.VariableSpec `ebpf:"health_blacklist_ns"`
	HealthThreshold     *ebpf.VariableSpec `ebpf:"health_threshold"`
	HealthWindowNs      *ebpf.VariableSpec `ebpf:"health_window_ns"`
	InitconnectBurst    *ebpf.VariableSpec `ebpf:"initconnect_burst"`
	InitconnectPeriodNs *ebpf.VariableSpec `ebpf:"initconnect_period_ns"`
	TcpGlobalBurst      *ebpf.VariableSpec `ebpf:"tcp_global_burst"`
	TcpGlobalPeriodNs   *ebpf.VariableSpec `ebpf:"tcp_global_period_ns"`
	TcpMaxOpenPerIp     *ebpf.VariableSpec `ebpf:"tcp_max_open_per_ip"`
	UdpBurst            *ebpf.VariableSpec `ebpf:"udp_burst"`
	UdpRefillPeriodNs   *ebpf.VariableSpec `ebpf:"udp_refill_period_ns"`
	WhitelistTtlNs      *ebpf.VariableSpec `ebpf:"whitelist_ttl_ns"`
}

// fivemXDPObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFivemXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type fivemXDPObjects struct {
	fivemXDPPrograms
	fivemXDPMaps
	fivemXDPVariables
}

func (o *fivemXDPObjects) Close() error {
	return _FivemXDPClose(
		&o.fivemXDPPrograms,
		&o.fivemXDPMaps,
	)
}

// fivemXDPMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFivemXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type fivemXDPMaps struct {
	FivemDropHistory     *ebpf.Map `ebpf:"fivem_drop_history"`
	FivemStats           *ebpf.Map `ebpf:"fivem_stats"`
	GetinfoRatelimit     *ebpf.Map `ebpf:"getinfo_ratelimit"`
	InitconnectRatelimit *ebpf.Map `ebpf:"initconnect_ratelimit"`
	TcpEstablished       *ebpf.Map `ebpf:"tcp_established"`
	TcpGlobalRatelimit   *ebpf.Map `ebpf:"tcp_global_ratelimit"`
	TcpOpenCount         *ebpf.Map `ebpf:"tcp_open_count"`
	TcpSynSeen           *ebpf.Map `ebpf:"tcp_syn_seen"`
	TcpWhitelist         *ebpf.Map `ebpf:"tcp_whitelist"`
	UdpHealth            *ebpf.Map `ebpf:"udp_health"`
	UdpRatelimit         *ebpf.Map `ebpf:"udp_ratelimit"`
}

func (m *fivemXDPMaps) Close() error {
	return _FivemXDPClose(
		m.FivemDropHistory,
		m.FivemStats,
		m.GetinfoRatelimit,
		m.InitconnectRatelimit,
		m.TcpEstablished,
		m.TcpGlobalRatelimit,
		m.TcpOpenCount,
		m.TcpSynSeen,
		m.TcpWhitelist,
		m.UdpHealth,
		m.UdpRatelimit,
	)
}

// fivemXDPVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFivemXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type fivemXDPVariables struct {
	GetinfoBurst        *ebpf.Variable `ebpf:"getinfo_burst"`
	GetinfoPeriodNs     *ebpf.Variable `ebpf:"getinfo_period_ns"`
	HealthBlacklistNs   *ebpf.Variable `ebpf:"health_blacklist_ns"`
	HealthThreshold     *ebpf.Variable `ebpf:"health_threshold"`
	HealthWindowNs      *ebpf.Variable `ebpf:"health_window_ns"`
	InitconnectBurst    *ebpf.Variable `ebpf:"initconnect_burst"`
	InitconnectPeriodNs *ebpf.Variable `ebpf:"initconnect_period_ns"`
	TcpGlobalBurst      *ebpf.Variable `ebpf:"tcp_global_burst"`
	TcpGlobalPeriodNs   *ebpf.Variable `ebpf:"tcp_global_period_ns"`
	TcpMaxOpenPerIp     *ebpf.Variable `ebpf:"tcp_max_open_per_ip"`
	UdpBurst            *ebpf.Variable `ebpf:"udp_burst"`
	UdpRefillPeriodNs   *ebpf.Variable `ebpf:"udp_refill_period_ns"`
	WhitelistTtlNs      *ebpf.Variable `ebpf:"whitelist_ttl_ns"`
}

// fivemXDPPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFivemXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type fivemXDPPrograms struct {
	GameshieldFivemXdp *ebpf.Program `ebpf:"gameshield_fivem_xdp"`
}

func (p *fivemXDPPrograms) Close() error {
	return _FivemXDPClose(
		p.GameshieldFivemXdp,
	)
}

func _FivemXDPClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed fivemxdp_bpfel.o
var _FivemXDPBytes []byte
