// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package core

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type dispatcherXDPRatelimit struct {
	Tokens       uint64
	LastRefillNs uint64
}

type dispatcherXDPUdpHealth struct {
	Anomalies        uint32
	_                [4]byte
	WindowStartNs    uint64
	BlacklistUntilNs uint64
}

// loadDispatcherXDP returns the embedded CollectionSpec for dispatcherXDP.
func loadDispatcherXDP() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DispatcherXDPBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load dispatcherXDP: %w", err)
	}

	return spec, err
}

// loadDispatcherXDPObjects loads dispatcherXDP and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*dispatcherXDPObjects
//	*dispatcherXDPPrograms
//	*dispatcherXDPMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDispatcherXDPObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDispatcherXDP()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// dispatcherXDPSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dispatcherXDPSpecs struct {
	dispatcherXDPProgramSpecs
	dispatcherXDPMapSpecs
	dispatcherXDPVariableSpecs
}

// dispatcherXDPProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dispatcherXDPProgramSpecs struct {
	GameshieldDispatchXdp *ebpf.ProgramSpec `ebpf:"gameshield_dispatch_xdp"`
}

// dispatcherXDPMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dispatcherXDPMapSpecs struct {
	PortRouter         *ebpf.MapSpec `ebpf:"port_router"`
	SockopsModules     *ebpf.MapSpec `ebpf:"sockops_modules"`
	TcpEstablished     *ebpf.MapSpec `ebpf:"tcp_established"`
	TcpGlobalRatelimit *ebpf.MapSpec `ebpf:"tcp_global_ratelimit"`
	TcpOpenCount       *ebpf.MapSpec `ebpf:"tcp_open_count"`
	TcpSynSeen         *ebpf.MapSpec `ebpf:"tcp_syn_seen"`
	TcpWhitelist       *ebpf.MapSpec `ebpf:"tcp_whitelist"`
	UdpHealth          *ebpf.MapSpec `ebpf:"udp_health"`
	UdpRatelimit       *ebpf.MapSpec `ebpf:"udp_ratelimit"`
	XdpModules         *ebpf.MapSpec `ebpf:"xdp_modules"`
}

// dispatcherXDPVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dispatcherXDPVariableSpecs struct {
}

// dispatcherXDPObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDispatcherXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type dispatcherXDPObjects struct {
	dispatcherXDPPrograms
	dispatcherXDPMaps
	dispatcherXDPVariables
}

func (o *dispatcherXDPObjects) Close() error {
	return _DispatcherXDPClose(
		&o.dispatcherXDPPrograms,
		&o.dispatcherXDPMaps,
	)
}

// dispatcherXDPMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDispatcherXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type dispatcherXDPMaps struct {
	PortRouter         *ebpf.Map `ebpf:"port_router"`
	SockopsModules     *ebpf.Map `ebpf:"sockops_modules"`
	TcpEstablished     *ebpf.Map `ebpf:"tcp_established"`
	TcpGlobalRatelimit *ebpf.Map `ebpf:"tcp_global_ratelimit"`
	TcpOpenCount       *ebpf.Map `ebpf:"tcp_open_count"`
	TcpSynSeen         *ebpf.Map `ebpf:"tcp_syn_seen"`
	TcpWhitelist       *ebpf.Map `ebpf:"tcp_whitelist"`
	UdpHealth          *ebpf.Map `ebpf:"udp_health"`
	UdpRatelimit       *ebpf.Map `ebpf:"udp_ratelimit"`
	XdpModules         *ebpf.Map `ebpf:"xdp_modules"`
}

func (m *dispatcherXDPMaps) Close() error {
	return _DispatcherXDPClose(
		m.PortRouter,
		m.SockopsModules,
		m.TcpEstablished,
		m.TcpGlobalRatelimit,
		m.TcpOpenCount,
		m.TcpSynSeen,
		m.TcpWhitelist,
		m.UdpHealth,
		m.UdpRatelimit,
		m.XdpModules,
	)
}

// dispatcherXDPVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDispatcherXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type dispatcherXDPVariables struct {
}

// dispatcherXDPPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDispatcherXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type dispatcherXDPPrograms struct {
	GameshieldDispatchXdp *ebpf.Program `ebpf:"gameshield_dispatch_xdp"`
}

func (p *dispatcherXDPPrograms) Close() error {
	return _DispatcherXDPClose(
		p.GameshieldDispatchXdp,
	)
}

func _DispatcherXDPClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dispatcherxdp_bpfel.o
var _DispatcherXDPBytes []byte
