// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package core

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadDispatcherSockops returns the embedded CollectionSpec for dispatcherSockops.
func loadDispatcherSockops() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DispatcherSockopsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load dispatcherSockops: %w", err)
	}

	return spec, err
}

// loadDispatcherSockopsObjects loads dispatcherSockops and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*dispatcherSockopsObjects
//	*dispatcherSockopsPrograms
//	*dispatcherSockopsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDispatcherSockopsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDispatcherSockops()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// dispatcherSockopsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dispatcherSockopsSpecs struct {
	dispatcherSockopsProgramSpecs
	dispatcherSockopsMapSpecs
	dispatcherSockopsVariableSpecs
}

// dispatcherSockopsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dispatcherSockopsProgramSpecs struct {
	GameshieldDispatchSockops *ebpf.ProgramSpec `ebpf:"gameshield_dispatch_sockops"`
}

// dispatcherSockopsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dispatcherSockopsMapSpecs struct {
	PortRouter     *ebpf.MapSpec `ebpf:"port_router"`
	SockopsModules *ebpf.MapSpec `ebpf:"sockops_modules"`
	XdpModules     *ebpf.MapSpec `ebpf:"xdp_modules"`
}

// dispatcherSockopsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dispatcherSockopsVariableSpecs struct {
}

// dispatcherSockopsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDispatcherSockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type dispatcherSockopsObjects struct {
	dispatcherSockopsPrograms
	dispatcherSockopsMaps
	dispatcherSockopsVariables
}

func (o *dispatcherSockopsObjects) Close() error {
	return _DispatcherSockopsClose(
		&o.dispatcherSockopsPrograms,
		&o.dispatcherSockopsMaps,
	)
}

// dispatcherSockopsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDispatcherSockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type dispatcherSockopsMaps struct {
	PortRouter     *ebpf.Map `ebpf:"port_router"`
	SockopsModules *ebpf.Map `ebpf:"sockops_modules"`
	XdpModules     *ebpf.Map `ebpf:"xdp_modules"`
}

func (m *dispatcherSockopsMaps) Close() error {
	return _DispatcherSockopsClose(
		m.PortRouter,
		m.SockopsModules,
		m.XdpModules,
	)
}

// dispatcherSockopsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDispatcherSockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type dispatcherSockopsVariables struct {
}

// dispatcherSockopsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDispatcherSockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type dispatcherSockopsPrograms struct {
	GameshieldDispatchSockops *ebpf.Program `ebpf:"gameshield_dispatch_sockops"`
}

func (p *dispatcherSockopsPrograms) Close() error {
	return _DispatcherSockopsClose(
		p.GameshieldDispatchSockops,
	)
}

func _DispatcherSockopsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dispatchersockops_bpfel.o
var _DispatcherSockopsBytes []byte
